### ISSUE TITLE
getter assertion called for unwrap method

### ISSUE THREAD

**Issue by basz** [validated-changeset/validated-changeset#62]
how is this possible??? The validate() method is calling `value.unwrap()`. Then the getter trap from the proxy is called?

This is from v0.6.3.

```
Ember Error: Assertion Failed: Cannot call get with 'unwrap' on an undefined object.
    at assert (https://localhost:4201/assets/vendor.js:42898:15)
    at Object.get (https://localhost:4201/assets/vendor.js:21706:72)
    at ObjectTreeNode.safeGet (https://localhost:4201/assets/vendor.js:172136:20)
    at Object.get (webpack://__ember_auto_import__//Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-lab/node_modules/validated-changeset/dist/validated-changeset.es5.js?:997:16)
    at eval (webpack://__ember_auto_import__//Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-lab/node_modules/validated-changeset/dist/validated-changeset.es5.js?:1983:67)
    at Array.map (<anonymous>)
    at Proxy.BufferedChangeset.validate (webpack://__ember_auto_import__//Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-lab/node_modules/validated-changeset/dist/validated-changeset.es5.js?:1980:39)
    at _class3.validateModelTask (task) (https://localhost:4201/assets/@plhw-lab/lab-plhw.js:47850:26)
    at Generator.next (<anonymous>)
    at Class._resumeGenerator (https://localhost:4201/assets/vendor.js:177800:46)
```

```
BufferedChangeset.prototype.validate = function () {
        var _this = this;
        var validationKeys = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            validationKeys[_i] = arguments[_i];
        }
        if (keys$1(this.validationMap).length === 0 && !validationKeys.length) {
            return Promise.resolve(null);
        }
        validationKeys =
            validationKeys.length > 0
                ? validationKeys
                : keys$1(flattenValidations(this.validationMap));
        var maybePromise = validationKeys.map(function (key) {
            var value = _this[key];
            var resolvedValue = value instanceof ObjectTreeNode ? value.unwrap() : value;
            return _this._validateKey(key, resolvedValue);
        });
        return Promise.all(maybePromise);
    };
```

`console.log(key, value , value instanceof ObjectTreeNode);` show the following

```
consumer.birthday
Proxy {changes: {…}, content: null, proxy: Proxy, children: {…}, safeGet: ƒ}
true
```
The proxy contains a momentjs object

**Comment by snewcomer** [comment]
Sort of guessing with the merged PR....
